---
title: "sampling"
author: "Lingyi Zhao, Sizhu Chen, Ye Yue"
date: "2018/10/29"
output: word_document
---

```{r}
library(dplyr)
library(tidyr)
library(stringr)
```

```{r}

training<-read.csv("training.csv",stringsAsFactors = F)
testing<-read.csv("testing.csv",stringsAsFactors = F)
total<-rbind(training, testing)

total<-total[-c(3,4,5,10:16)]
#save(total, file="total.csv")
#save(total, file="total.RData")
```

```{r}
library(miceadds)
total<-load.Rdata2("total.RData")

```

Sepreate all genre
```{r}

usercount<-count(total, vars=total$msno)

top_10000<-function(df, col){
  temp_df<-df %>%
    arrange(desc(n))%>%
    print
  return(temp_df)
}


vvtop<-top_10000(usercount, usercount$n)[1:1000,]

merge<-subset(total, msno %in% vvtop$vars)

```

```{r songpool establish}

songpool<-count(total, var=song_id)
names(songpool)<-c("song_id","fre")


total_pool<-total[,c(2,5,6)]
total_pool<-total_pool[!duplicated(total_pool),]# nrow=nrow(songpool)
total_pool<-merge(total_pool,songpool,by="song_id")

#expand total_pool by genre

cot1<-rep(NA,nrow(total_pool))
for (i in 1:nrow(total_pool)){
  cot1[i]<-str_count(total_pool$genre_ids[i],"\\|")+1
}
total_pool_expand<- total_pool[rep(row.names(total_pool), cot1),]

genre_split1<-unlist(strsplit(total_pool$genre_ids,"\\|"))
total_pool_expand$genre_ids<-genre_split1 
total_pool<-total_pool_expand

total_pool<-total_pool[order(total_pool$fre,decreasing = T),]

```

```{r separate train test}
 
 vvtop$train_num<-round(vvtop$n*0.7)
 train<-data.frame() 
 for(i in 1:nrow(vvtop)){
   each_user<-subset(merge,msno==vvtop$vars[i])
   set.seed(2018)
   trainset<-each_user[sample(1:nrow(each_user),size = vvtop$train_num[i]),]
   train<-rbind(train,trainset)
 }
 
 test<-setdiff(merge, train)
```

```{r, expand train}

cot2<-rep(NA,nrow(train))
for (i in 1:nrow(train)){
  cot2[i]<-str_count(train$genre_ids[i],"\\|")+1
}

train_expanded <- train[rep(row.names(train), cot2),]
train_expanded$genre_ids<-unlist(strsplit(train$genre_ids,"\\|")) 
trainset<-train_expanded

```

```{r get top pair}

top_features<-data.frame()
top_genres<-data.frame()
top_languages<-data.frame()
top_artists<-data.frame()

for (h in vvtop$vars){
  top_genre<-as.numeric(names(sort(table(trainset$genre_ids[trainset$msno==h]),
                                   decreasing = TRUE))[1])
  top_genres<-rbind(top_genres,top_genre)
  
  top_language<-as.numeric(names(sort(table(trainset$language [trainset$msno==h]),
                                      decreasing = TRUE))[1])
  top_languages<-rbind(top_languages,top_language)
  
}
top_features<-cbind(vvtop$vars ,top_genres, top_languages)
names(top_features)<-c("Users","genre","language")

```

Recommend music based on (genre, language, artist) and users should not listen these music before
```{r recommend, warning=FALSE}
recom_set<-data.frame()
recom_table<-data.frame()

  for (g in top_features$Users){
  
  recom_set<-subset(total_pool,
                             !(song_id %in% trainset$song_id[trainset$msno==g]))
  recommend<-subset(recom_set, 
                    recom_set$genre_ids ==top_features$genre[top_features$Users==g] &
                      recom_set$language == top_features$language[top_features$Users==g])

  
  if(nrow(recommend)==0){
    recommend<-recom_set$song_id[1:10]
  }
  else{
  recommend<-recommend$song_id[1:10]}
  
  recom_table<-rbind(recom_table,
                     data.frame(users=rep(g,10),recom_music=recommend))

}


#save(recom_table,file = "recommends_final_1000.RData")
```


```{r}

test_target1<-test[test$target==1,]

score<-NULL

for (p in unique(recom_table$users)){
  testsong<-test_target1$song_id[test_target1$msno==p]
  score<-c(score,sum(testsong %in% recom_table$recom_music[recom_table$users==p]))
  
}
testerror<-1-sum(score)/(10*nrow(vvtop))
testerror
```

